### ISSUE TITLE
Don't lose quality using the model on iOS

### ISSUE THREAD

**Issue by vittorionapoli** [mallman/CoreMLaMa#2]
Hi,
starting used the CoreML model inside a photo editor application,  main problem is the 800x800 limit (tried to increase it but having problem on memory). I tried to split the image to 800x800 and then do the erasing but the result isn't good.

Do you have thoughts?

**Comment by codenia** [comment]
The size of 800 x 800 will already lead to a crash on non-latest device generations. If you want to use it on iOS, then you should use 512x512 pixels. You should crop the image to the masked area with some margin before processing. After inpainting, you should enlarge it with a second AI model to improve the quality. As there is still relatively little memory available on mobile devices, it is necessary to implement a creative solution in order to achieve a reasonably good result.

**Comment by mallman** [comment]
Hi Vittorio,

I don't have experience using this model on iOS, and I don't have any advice for doing so.

With respect to the fixed crop size, I have not been able to configure the model conversion script to work with arbitrary crop sizes. While CoreML supports image input with arbitrary sizes, it's not sophisticated enough to support the particular use case for LaMa. That is as of CoreML tools version 6.3.

CoreML tools 7.0 advertises new model compression and optimization capabilities that may make a deployment to limited-resource devices like the iPhone more feasible. Since my particular use case for CoreMLaMa is for macOS only and I have many other projects to work on, I don't anticipate working on optimizing CoreMLaMa for iOS.

**Comment by vittorionapoli** [comment]
Hi mailman, thanks for your response!
How do you use the model for processing non square images on your macOS App?

**Comment by mallman** [comment]
Hi Vittorio,

I crop an 800x800 image from the full image for processing. The crop surrounds the mask that the user draws. Once the image and mask are processed by LaMa, you just replace the original cropped area of your input image with the inpainted crop.

This is what the sample program does. Have you seen it? [main.swift](https://github.com/mallman/CoreMLaMa/blob/master/Sample/Sources/Sample/main.swift)

If I have some time I'll put together a clearer illustration of the process.
